# Generated by Django 5.2.5 on 2025-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_otp_code_user_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('combo', 'Combo')], default='food', max_length=20),
        ),
    ]
